const dummyData = {
    "flowers": [
        {
            "name": "Strawflower",
            "type": "Filler",
            "unit": "bunch",
            "price": 3.00,
            "priceRange": "$$",
            "photoName": "strawflower.png",
            "color": "orange",
            "meaning": "joy, happiness and adventure",
            "valentines": false,
            "easter": false,
            "romance": false,
            "appreciation": true,
            "apology": false,
            "fun": true,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Spray Roses",
            "type": "Filler",
            "unit": "stem",
            "price": 2.00,
            "priceRange": "$",
            "photoName": "sprayrose.png",
            "color": "pink",
            "meaning": "gratitude",
            "valentines": false,
            "easter": true,
            "romance": false,
            "appreciation": true,
            "apology": false,
            "fun": false,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Queen Anne's Lace",
            "type": "Filler",
            "unit": "bunch",
            "price": 4.00,
            "priceRange": "$$$",
            "photoName": "queenanneslace.png",
            "color": "white",
            "meaning": "safety",
            "valentines": true,
            "easter": true,
            "romance": true,
            "appreciation": true,
            "apology": false,
            "fun": true,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Lavender",
            "type": "Filler",
            "unit": "bunch",
            "price": 4.00,
            "priceRange": "$$$",
            "photoName": "lavender.png",
            "color": "purple",
            "meaning": "serenity, devotion",
            "valentines": false,
            "easter": true,
            "romance": false,
            "appreciation": true,
            "apology": true,
            "fun": false,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Daisy",
            "type": "Filler",
            "unit": "bunch",
            "price": 2.00,
            "priceRange": "$",
            "photoName": "daisy.png",
            "color": "white",
            "meaning": "love, loyalty",
            "valentines": true,
            "easter": true,
            "romance": true,
            "appreciation": true,
            "apology": false,
            "fun": false,
            "partner": true,
            "familyMember": false,
            "friend": true
        },
        {
            "name": "Tulip",
            "type": "Focal",
            "unit": "stem",
            "price": 3.00,
            "priceRange": "$",
            "photoName": "tulip.png",
            "color": "purple",
            "meaning": "deep love",
            "valentines": true,
            "easter": true,
            "romance": true,
            "appreciation": true,
            "apology": false,
            "fun": true,
            "partner": true,
            "familyMember": true,
            "friend": false
        },
        {
            "name": "Red Rose",
            "type": "Focal",
            "unit": "stem",
            "price": 4.00,
            "priceRange": "$$",
            "photoName": "redrose.png",
            "color": "red",
            "meaning": "love, passion",
            "valentines": true,
            "easter": false,
            "romance": true,
            "appreciation": true,
            "apology": true,
            "fun": true,
            "partner": false,
            "familyMember": false,
            "friend": true
        },
        {
            "name": "Hydrangea",
            "type": "Focal",
            "unit": "stem",
            "price": 5.00,
            "priceRange": "$$$",
            "photoName": "hydrangea.png",
            "color": "blue",
            "meaning": "gratitude",
            "valentines": false,
            "easter": true,
            "romance": false,
            "appreciation": true,
            "apology": false,
            "fun": false,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Garden Rose",
            "type": "Focal",
            "unit": "stem",
            "price": 5.00,
            "priceRange": "$$$",
            "photoName": "gardenrose.png",
            "color": "pink",
            "meaning": "love, romance",
            "valentines": true,
            "easter": false,
            "romance": true,
            "appreciation": true,
            "apology": false,
            "fun": true,
            "partner": false,
            "familyMember": false,
            "friend": true
        },
        {
            "name": "Dahlia",
            "type": "Focal",
            "unit": "bunch",
            "price": 4.00,
            "priceRange": "$$",
            "photoName": "dahlia.png",
            "color": "red",
            "meaning": "eternal love, kindness",
            "valentines": true,
            "easter": true,
            "romance": true,
            "appreciation": true,
            "apology": false,
            "fun": false,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Carnation",
            "type": "Focal",
            "unit": "stem",
            "price": 3.00,
            "priceRange": "$",
            "photoName": "carn.png",
            "color": "red",
            "meaning": "distinction, love",
            "valentines": true,
            "easter": false,
            "romance": true,
            "appreciation": true,
            "apology": false,
            "fun": false,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Ruscus",
            "type": "Foliage",
            "unit": "bunch",
            "price": 5.00,
            "priceRange": "$$",
            "photoName": "ruscus.png",
            "color": "green",
            "meaning": "thoughtfulness",
            "valentines": true,
            "easter": true,
            "romance": true,
            "appreciation": true,
            "apology": false,
            "fun": false,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Nagi",
            "type": "Foliage",
            "unit": "bunch",
            "price": 6.00,
            "priceRange": "$$$",
            "photoName": "nagi.png",
            "color": "green",
            "meaning": "",
            "valentines": true,
            "easter": true,
            "romance": true,
            "appreciation": true,
            "apology": true,
            "fun": true,
            "partner": true,
            "familyMember": true,
            "friend": true
        },
        {
            "name": "Leather Leaf",
            "type": "Foliage",
            "unit": "bunch",
            "price": 4.00,
            "priceRange": "$",
            "photoName": "leatherleaf.png",
            "color": "green",
            "meaning": "delicate attention",
            "valentines": true,
            "easter": true,
            "romance": true,
            "appreciation": true,
            "apology": true,
            "fun": false,
            "partner": false,
            "familyMember": false,
            "friend": false
        },
        {
            "name": "Ivy",
            "type": "Foliage",
            "unit": "bunch",
            "price": 6.00,
            "priceRange": "$$$",
            "photoName": "ivy.png",
            "color": "green",
            "meaning": "everlasting love, loyalty",
            "valentines": true,
            "easter": true,
            "romance": true,
            "appreciation": true,
            "apology": true,
            "fun": false,
            "partner": false,
            "familyMember": false,
            "friend": false
        }
    ]
}
export default dummyData;