const dummyData = {
    "flowers": [
        {
            "name": "Strawflower",
            "type": "Filler",
            "unit": "bunch",
            "price": 3.00,
            "priceRange": "$$",
            "photoName": "strawflower.png",
            "color": "orange",
            "meaning": "joy, happiness and adventure",
            "occasion": ["appreciation", "fun"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Spray Roses",
            "type": "Filler",
            "unit": "stem",
            "price": 2.00,
            "priceRange": "$",
            "photoName": "sprayrose.png",
            "color": "pink",
            "meaning": "gratitude",
            "occasion": ["easter", "appreciation"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Queen Anne's Lace",
            "type": "Filler",
            "unit": "bunch",
            "price": 4.00,
            "priceRange": "$$$",
            "photoName": "queenanneslace.png",
            "color": "white",
            "meaning": "safety",
            "occasion": ["valentines", "easter", "romance", "appreciation"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Lavender",
            "type": "Filler",
            "unit": "bunch",
            "price": 4.00,
            "priceRange": "$$$",
            "photoName": "lavender.png",
            "color": "purple",
            "meaning": "serenity, devotion",
            "occasion": ["easter", "appreciation", "apology"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Daisy",
            "type": "Filler",
            "unit": "bunch",
            "price": 2.00,
            "priceRange": "$",
            "photoName": "daisy.png",
            "color": "white",
            "meaning": "love, loyalty",
            "occasion": ["valentines", "easter", "romance", "appreciation"],
            "shoppingFor": ["partner", "friend"]
        },
        {
            "name": "Tulip",
            "type": "Focal",
            "unit": "stem",
            "price": 3.00,
            "priceRange": "$",
            "photoName": "tulip.png",
            "color": "purple",
            "meaning": "deep love",
            "occasion": ["valentines", "easter", "romance", "appreciation", "fun"],
            "shoppingFor": ["partner", "familyMember"]
        },
        {
            "name": "Red Rose",
            "type": "Focal",
            "unit": "stem",
            "price": 4.00,
            "priceRange": "$$",
            "photoName": "redrose.png",
            "color": "red",
            "meaning": "love, passion",
            "occasion": ["valentines", "romance", "appreciation", "apology", "fun"],
            "shoppingFor": ["friend"]
        },
        {
            "name": "Hydrangea",
            "type": "Focal",
            "unit": "stem",
            "price": 5.00,
            "priceRange": "$$$",
            "photoName": "hydrangea.png",
            "color": "blue",
            "meaning": "gratitude",
            "occasion": ["easter", "appreciation"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Garden Rose",
            "type": "Focal",
            "unit": "stem",
            "price": 5.00,
            "priceRange": "$$$",
            "photoName": "gardenrose.png",
            "color": "pink",
            "meaning": "love, romance",
            "occasion": ["valentines", "romance", "appreciation", "fun"],
            "shoppingFor": ["friend"]
        },
        {
            "name": "Dahlia",
            "type": "Focal",
            "unit": "bunch",
            "price": 4.00,
            "priceRange": "$$",
            "photoName": "dahlia.png",
            "color": "red",
            "meaning": "eternal love, kindness",
            "occasion": ["valentines", "easter", "romance", "appreciation"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Carnation",
            "type": "Focal",
            "unit": "stem",
            "price": 3.00,
            "priceRange": "$",
            "photoName": "carn.png",
            "color": "red",
            "meaning": "distinction, love",
            "occasion": ["valentines", "romance", "appreciation"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Ruscus",
            "type": "Foliage",
            "unit": "bunch",
            "price": 5.00,
            "priceRange": "$$",
            "photoName": "ruscus.png",
            "color": "green",
            "meaning": "thoughtfulness",
            "occasion": ["valentines", "easter", "romance", "appreciation"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Nagi",
            "type": "Foliage",
            "unit": "bunch",
            "price": 6.00,
            "priceRange": "$$$",
            "photoName": "nagi.png",
            "color": "green",
            "meaning": "",
            "occasion": ["valentines", "easter", "romance", "appreciation", "apology", "fun"],
            "shoppingFor": ["partner", "familyMember", "friend"]
        },
        {
            "name": "Leather Leaf",
            "type": "Foliage",
            "unit": "bunch",
            "price": 4.00,
            "priceRange": "$",
            "photoName": "leatherleaf.png",
            "color": "green",
            "meaning": "delicate attention",
            "occasion": ["valentines", "easter", "romance", "appreciation", "apology"],
            "shoppingFor": []
        },
        {
            "name": "Ivy",
            "type": "Foliage",
            "unit": "bunch",
            "price": 6.00,
            "priceRange": "$$$",
            "photoName": "ivy.png",
            "color": "green",
            "meaning": "everlasting love, loyalty",
            "occasion": ["valentines", "easter", "romance", "appreciation", "apology"],
            "shoppingFor": []
        }
    ]
}
export default dummyData;